openapi: 3.0.1
info:
  title: Gestão de Contas
  description: Abra e gerencie contas de pagamento do seu cliente pessoa física ou jurídica.
  version: '1.0'
servers:
  - url: https://api.sandbox.bankly.com.br
paths:
  /accounts/{accountNumber}:
    get:
      tags:
        - Conta de pagamentos
      summary: Obtenha dados da conta de pagamentos.
      description: |
        <div class="bkly-ref-description">
          <p>Opcionalmente você pode obter o saldo desta conta.</p> 
          <span class="bkly-ref-small-stable-tag">stable</span> <span class="bkly-ref-scope-tag">scope: account.read</span>
        </div>  
      operationId: GetAccount
      parameters:
        - $ref: '#/components/parameters/AccountNumber'
        - $ref: '#/components/parameters/ApiVersion'
        - $ref: '#/components/parameters/IncludeBalance'
      responses:
        '200':
          description: Recurso encontrado.
          headers:
            x-bkly-correlation-id:
              $ref: '#/components/headers/CorrelationId'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountDetailedResponse'
              examples:
                  accountBasicExample:
                      $ref: '#/components/examples/accountBasicExample'
                  accountDetailedExample:
                      $ref: '#/components/examples/accountDetailedExample'
        '400':
          $ref: '#/components/responses/400'
        '403':
          $ref: '#/components/responses/403'
        '409':
          $ref: '#/components/responses/409'
        '422':
          $ref: '#/components/responses/422'
        '500':
          $ref: '#/components/responses/500'
  /customers/{documentNumber}/accounts:
    get:
      tags:
        - Conta pessoa física
      summary: Obtenha as contas de pagamento de um cliente.
      description: |
        <div class="bkly-ref-description">
          <p>Retornaremos uma lista com todas as contas desse cliente, independentemente de seus respectivos status.</p> 
          <span class="bkly-ref-small-stable-tag">stable</span> <span class="bkly-ref-scope-tag">scope: account.read</span>
        </div>
      operationId: GetPersonalAccounts
      parameters:
        - $ref: '#/components/parameters/CustomerDocument'
        - $ref: '#/components/parameters/ApiVersion'
      responses:
        '200':
          description: Recurso encontrado.
          headers:
            x-bkly-correlation-id:
              $ref: '#/components/headers/CorrelationId'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AccountBasicResponse'
              examples:
                  listOfAccounts:
                    $ref: '#/components/examples/listOfAccounts'
        '400':
          $ref: '#/components/responses/400'
        '403':
          $ref: '#/components/responses/403'
        '409':
          $ref: '#/components/responses/409'
        '422':
          $ref: '#/components/responses/422'
        '500':
          $ref: '#/components/responses/500'
    post:
      tags:
        - Conta pessoa física
      summary: Crie uma conta de pagamentos pessoa física.
      description: |
        <div class="bkly-ref-description">
          <p>O cliente poderá ter até 5 contas de pagamento, no entanto é necessário ter o registro do titular (pessoa física) previamente aprovado.</p>
          <span class="bkly-ref-small-stable-tag">stable</span> <span class="bkly-ref-scope-tag">scope: account.create</span>
        </div>
        [block:callout]
        {
          "type": "warning",
          "title": "Importante",
          "body": "Considere o uso do header ```Idempotency-Key``` afim de evitar criar contas indesejadas."
        }
        [/block]  
      operationId: CreatePersonalAccount
      parameters:
        - $ref: '#/components/parameters/CustomerDocument'
        - $ref: '#/components/parameters/ApiVersion'
        - $ref: '#/components/parameters/IdempotencyKey'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateAccountRequest'
      responses:
        '201':
          description: Recurso criado com sucesso.
          headers:
            x-bkly-correlation-id:
              $ref: '#/components/headers/CorrelationId'
            Location:
              $ref: '#/components/headers/Location'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountDetailedResponse'
              examples:
                  accountDetailedExample:
                      $ref: '#/components/examples/accountDetailedExample'
        '400':
          $ref: '#/components/responses/400'
        '403':
          $ref: '#/components/responses/403'
        '409':
          $ref: '#/components/responses/409'
        '422':
          $ref: '#/components/responses/422'
        '500':
          $ref: '#/components/responses/500'
  /business/{documentNumber}/accounts:
    get:
      tags:
        - Conta pessoa jurídica
      summary: Obtenha as contas de pagamento de uma empresa.
      description: |
          <div class="bkly-ref-description">
            <p>Retornaremos uma lista com todas as contas dessa empresa, independentemente de seus respectivos status.</p>
            <span class="bkly-ref-small-stable-tag">stable</span> <span class="bkly-ref-scope-tag">scope: account.read</span>
          </div>  
      operationId: GetBusinessAccounts
      parameters:
        - $ref: '#/components/parameters/BusinessDocument'
        - $ref: '#/components/parameters/ApiVersion'
      responses:
        '200':
          description: Recurso encontrado.
          headers:
            x-bkly-correlation-id:
              $ref: '#/components/headers/CorrelationId'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AccountBasicResponse'
              examples:
                  listOfAccounts:
                    $ref: '#/components/examples/listOfAccounts'
        '400':
          $ref: '#/components/responses/400'
        '403':
          $ref: '#/components/responses/403'
        '409':
          $ref: '#/components/responses/409'
        '422':
          $ref: '#/components/responses/422'
        '500':
          $ref: '#/components/responses/500'
    post:
      tags:
        - Conta pessoa jurídica
      summary: Crie uma conta de pagamentos para uma empresa (MEI, EI ou EIRELLI).
      description: |
        <div class="bkly-ref-description">
          <p>A empresa poderá ter até 5 contas de pagamento, no entanto é necessário ter o registro do titular (pessoa jurídica) previamente aprovado.</p>
          <span class="bkly-ref-small-stable-tag">stable</span> <span class="bkly-ref-scope-tag">scope: account.create</span>
        </div>  
        [block:callout]
        {
          "type": "warning",
          "title": "Importante",
          "body": "Considere o uso do header ```Idempotency-Key``` afim de evitar criar contas indesejadas."
        }
        [/block] 
      operationId: CreateBusinessAccount
      parameters:
        - $ref: '#/components/parameters/BusinessDocument'
        - $ref: '#/components/parameters/ApiVersion'
        - $ref: '#/components/parameters/IdempotencyKey' 
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateAccountRequest'
      responses:
        '201':
          description: Recurso criado com sucesso.
          headers:
            x-bkly-correlation-id:
              $ref: '#/components/headers/CorrelationId'
            Location:
              $ref: '#/components/headers/Location'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountDetailedResponse'
              examples:
                  accountDetailedExample:
                      $ref: '#/components/examples/accountDetailedExample'
        '400':
          $ref: '#/components/responses/400'
        '403':
          $ref: '#/components/responses/403'
        '409':
          $ref: '#/components/responses/409'
        '422':
          $ref: '#/components/responses/422'
        '500':
          $ref: '#/components/responses/500'
  
security:
  - Bearer: []

components:
  
  parameters:
    ApiVersion:
      name: api-version
      in: header
      description: |
        Versão da API. 
        _Atualmente estamos na **1.0**._
      required: true
      style: simple
      explode: false
      schema:
        type: string
        default: 1
    IdempotencyKey:
      name: Idempotency-Key
      in: header
      description: Chave de idempotêcia para a requisição (uuid v4).
      required: false
      style: simple
      explode: false
      schema:
        type: string
    AccountNumber:
      name: accountNumber
      in: path
      description: |
        Número da conta de pagamento.
      required: true
      style: simple
      explode: false
      schema:
        $ref: '#/components/schemas/AccountNumber'
    CustomerDocument:
      name: documentNumber
      in: path
      description: |
        Número do documento CPF do cliente. 
        **_Informe somente os números._**
      required: true
      style: simple
      explode: false
      schema:
        $ref: '#/components/schemas/CustomerDocument'
    BusinessDocument:
      name: documentNumber
      in: path
      description: |
        Número do documento CNPJ da empresa. 
        **_Informe somente os números._**
      required: true
      style: simple
      explode: false
      schema:
        $ref: '#/components/schemas/BusinessDocument'
    IncludeBalance:
      name: includeBalance
      in: query
      description: Inclua o saldo da conta na pesquisa.
      required: false
      style: form
      explode: true
      schema:
        type: boolean
        default: false
  
  schemas:
    Error:
      type: object
      properties:
        code:
          description: Código do erro.
          type: string
          nullable: true
        propertyName:
          description: Parametro ou propriedade com problema. Somente será retornado quando o erro for de sintaxe (Bad Request). 
          type: string
          nullable: true
        messages:
          description: Lista de descrições do problema encontrado. 
          type: array
          nullable: true
          items:
            type: string
      additionalProperties: false
    ErrorResponse:
      description: Detalhes do erro identificado.
      type: object
      properties:
        errors:
          description: Lista de erros identificados. Trate-os antes de tentar novamente.
          type: array
          nullable: true
          items:
            $ref: '#/components/schemas/Error'
        reference:
          type: integer
          format: int32
      additionalProperties: false  
    BankBranch:
      type: string
      minLength: 4
      maxLength: 4
      description: |
        Agencia bancária.
        _Default: **0001**._    
    AccountNumber:
      description: Número da conta de pagamento.
      type: string
      minLength: 3
      maxLength: 13
    CustomerDocument:
      description: Número do documento CPF do titular da conta.
      type: string
      maxLength: 11
      minLength: 11
    BusinessDocument:
      description: Número do documento CNPJ do titular da conta.
      type: string
      maxLength: 14
      minLength: 14
    Balance:
      description: Saldo da conta.
      type: object
      properties:
        amount:
          description: |
            Valor em decimal. Ex: 1.00.
          type: number
          format: double
        currency:
          description: |
            Moeda corrente. _Default: *BRL*_
          type: string
      additionalProperties: false
    SummarizedBalance:
      description: Saldo sumarizado da conta.
      type: object
      properties:
        inProcess:
          description: Saldo em processamento _(cash in)_.
          $ref: '#/components/schemas/Balance'
        available:
          description: Saldo disponível.
          $ref: '#/components/schemas/Balance'
        blocked:
          description: Saldo em bloqueio judicial.
          $ref: '#/components/schemas/Balance'
      additionalProperties: false
    AccountStatus:
      type: string
      description: |
        Status da conta.
        _(ACTIVE, CLOSED)_
      enum:
        - ACTIVE
        - CLOSED
    AccountType:
      type: string
      description: |
        Tipo da conta a ser criada. 
        _Default: **PAYMENT_ACCOUNT**_.
      default: PAYMENT_ACCOUNT
      enum:
        - PAYMENT_ACCOUNT
    CreateAccountRequest:
      type: object
      properties:
        accountType:
          $ref: '#/components/schemas/AccountType'
      additionalProperties: false
    AccountBasicResponse:
      type: object
      properties:
        status:
          $ref: '#/components/schemas/AccountStatus'
        branch:
          $ref: '#/components/schemas/BankBranch'
        number:
          $ref: '#/components/schemas/AccountNumber'
      additionalProperties: false
    AccountDetailedResponse:
      type: object
      properties:
        balance:
          $ref: '#/components/schemas/SummarizedBalance'
        status:
          $ref: '#/components/schemas/AccountStatus'
        branch:
          $ref: '#/components/schemas/BankBranch'
        number:
          $ref: '#/components/schemas/AccountNumber'
      additionalProperties: false
  
  headers:
    CorrelationId:
      description: Id correlação da operação requisitada.
      style: simple
      explode: false
      schema:
        type: string
    Location:
      description: Localização do recurso recém-criado ou em análise.
      style: simple
      explode: false
      schema:
        type: string

  responses:
    '202':
      description: Requisição foi aceita e está sendo processada.
      headers:
        x-bkly-correlation-id:
          $ref: '#/components/headers/CorrelationId'
        Location:
          $ref: '#/components/headers/Location'
    '400':
      description: Há algum problema com a sua requisição.
      headers:
        x-bkly-correlation-id:
          $ref: '#/components/headers/CorrelationId'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          examples:
            accountDetailedExample:
              $ref: '#/components/examples/invalidParameterErrorResponse'
    '403':
      description: |
        O acesso ao recurso foi negado pelo servidor.
      headers:
        x-bkly-correlation-id:
          $ref: '#/components/headers/CorrelationId'
    '404':
      description: |
        Recurso não encontrado.
      headers:
        x-bkly-correlation-id:
          $ref: '#/components/headers/CorrelationId'
    '409':
      description: |
        A solicitação conflitou com o estado atual do recurso existente no servidor.
      headers:
        x-bkly-correlation-id:
          $ref: '#/components/headers/CorrelationId'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          examples:
            accountDetailedExample:
              $ref: '#/components/examples/errorResponse'
    '422':
      description: |
        A sintaxe da requisição esta correta, mas não foi possível processar devido uma regra de negócio.
      headers:
        x-bkly-correlation-id:
          $ref: '#/components/headers/CorrelationId'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          examples:
            accountDetailedExample:
              $ref: '#/components/examples/errorResponse'
    '500':
      description: |
        Ocorreu algum erro inexperado no nosso servidor.
      headers:
        x-bkly-correlation-id:
          $ref: '#/components/headers/CorrelationId'

  securitySchemes:
    Bearer:
      type: http
      description: Inclua o token de autorização do tipo Bearer
      scheme: bearer
      bearerFormat: JWT

  examples:
    invalidParameterErrorResponse:
      value:
        errors:
            - code: "INVALID_PARAMETER"  
              propertyName: '{{propertyName}}'
              messages:
                - '{{"propertyName" error message}}'
      summary: Parametro inválido

    errorResponse:
      value:
        errors:
            - code: "SOME_ERROR_CODE"  
              messages:
                - '{{Some error message}}'
      summary: Erro de negócio         

    accountBasicExample:
      value:
        branch: '0001'  
        number: '123456'
        status: 'ACTIVE'
      summary: Conta de pagamento sem saldo

    accountDetailedExample:
      value:
        branch: '0001'  
        number: '123456'
        status: 'ACTIVE'
        balance: 
          available:
              amount: 0.00
              currency: 'BRL'
          inProcess:
              amount: 0.00
              currency: 'BRL'
          blocked:
              amount: 0.00
              currency: 'BRL'  
      summary: Conta de pagamento com saldo
      
    listOfAccounts:
      value:
        - number: '123456'
          branch: '0001'  
          status: 'ACTIVE'
        - number: '123'
          branch: '0001'  
          status: 'CLOSED'
      summary: Lista de contas de pagamento

x-readme:
  explorer-enabled: true
  proxy-enabled: true
  samples-enabled: true
  samples-languages:
    - curl