openapi: 3.0.3
info:
  title: Gestão de Clientes
  description: |
    Registre, atualize, consulte o cadasto de clientes pessoa física ou
    jurídica. Um cliente com cadastro pode se tornar titular de contas de
    pagamento e cartões de crédito (pré-pago).
  version: '1.0'
servers:
  - url: 'https://api.sandbox.bankly.com.br'
paths:
  '/customers/{documentNumber}':
    get:
      tags:
        - Pessoa física
      summary: |
        Obtenha o registro do cliente.
      description: |
        <div class="bkly-ref-description">
          <p>Você pode obter um resultado resumido (BASIC) ou detalhado (DETAILED).</p> 
          <span class="bkly-ref-small-stable-tag">stable</span> <span class="bkly-ref-scope-tag">scope: customer.read</span>
        </div>
      operationId: GetCustomerRegistration
      parameters:
        - $ref: '#/components/parameters/CustomerDocument'
        - $ref: '#/components/parameters/ApiVersion'
        - $ref: '#/components/parameters/ResultLevel'
      responses:
        '200':
          description: Recurso encontrado
          headers:
            x-bkly-correlation-id:
              $ref: '#/components/headers/CorrelationId'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerResponse'
              examples:
                CustomerApproved:
                  value:
                    registerName: Peter Benjamin Parker
                    socialName: Peter Parker
                    birthDate: '1990-10-14'
                    phone:
                      countryCode: '55'
                      number: '11987654321'
                    address:
                      zipcode: '05402100'
                      addressLine: Av. Rebouças
                      buildingNumber: '1368'
                      neighborhood: Pinheiros
                      country: BR
                      state: SP
                      city: Sao Paulo
                      complement: Sala roxa
                    isPoliticallyExposedPerson: false
                    motherName: Mary Parker
                    email: peter.parker@avengers.com
                    status: APPROVED
                    createdAt: '2021-08-31T21:20:58.754Z'
                    updatedAt: '2021-08-31T21:21:58.754Z'
                  summary: Approved Customer
                CustomerReproved:
                  value:
                    registerName: Peter Parker
                    socialName: Peter Parker
                    birthDate: '1990-10-14'
                    phone:
                      countryCode: '55'
                      number: '11987654321'
                    address:
                      zipcode: '05402100'
                      addressLine: Av. Rebouças
                      buildingNumber: '1368'
                      neighborhood: Pinheiros
                      country: BR
                      state: SP
                      city: Sao Paulo
                      complement: Sala roxa
                    isPoliticallyExposedPerson: false
                    motherName: Mary Parker
                    email: peter.parker@avengers.com
                    status: REPROVED
                    reasons:
                      - SELFIE_RECUSED
                      - NAME_RECUSED
                    createdAt: '2021-08-31T21:20:58.754Z'
                    updatedAt: '2021-08-31T21:21:58.754Z'
                  summary: Reproved Customer
        '400':
          $ref: '#/components/responses/400'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'
    put:
      tags:
        - Pessoa física
      summary: |
        Registre ou atualize dos dados de um cliente pessoa física.
      description: |
        <div class="bkly-ref-description">
          <p>O pedido de registro será analisado e resultado você pode obter consultando o registro do cliente. Caso o cliente não exista ele será criado, caso contrario seus dados serão sobrepostos.</p>
          <span class="bkly-ref-small-stable-tag">stable</span> <span class="bkly-ref-scope-tag">scope: customer.write</span>
        </div>      
        [block:callout]
        {
          "type": "warning",
          "title": "Importante",
          "body": "Os possíveis status do cliente após essa análise são: APPROVED, REPROVED, REVOKED ou BLOCKED."
        }
        [/block]
      operationId: PutCustomerRegistration
      parameters:
        - $ref: '#/components/parameters/CustomerDocument'
        - $ref: '#/components/parameters/ApiVersion'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterCustomerRequest'
      responses:
        '202':
          $ref: '#/components/responses/202'
        '400':
          $ref: '#/components/responses/400'
        '409':
          $ref: '#/components/responses/409'
        '422':
          $ref: '#/components/responses/422'
        '500':
          $ref: '#/components/responses/500'
  '/business/{documentNumber}':
    get:
      tags:
        - Pessoa jurídica
      summary: |
        Obtenha o registro da empresa.
      description: |
        <div class="bkly-ref-description">
          <p>Você pode obter um resultado resumido (BASIC) ou detalhado (DETAILED).</p> 
          <span class="bkly-ref-small-stable-tag">stable</span> <span class="bkly-ref-scope-tag">scope: business.read</span>
        </div>      
      operationId: GetBusinessRegistration
      parameters:
        - $ref: '#/components/parameters/BusinessDocument'
        - $ref: '#/components/parameters/ApiVersion'
        - $ref: '#/components/parameters/ResultLevel'
      responses:
        '200':
          description: Recurso encontrado
          headers:
            x-bkly-correlation-id:
              $ref: '#/components/headers/CorrelationId'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BusinessResponse'
              examples:
                BusinessApproved:
                  value:
                    businessName: Peter Benjamin Parker
                    tradingName: Spider Man
                    businessEmail: spiderman@avengers.com
                    businessType: MEI
                    businessSize: MEI
                    businessAddress:
                      zipCode: '05402100'
                      addressLine: Av. Rebouças
                      buildingNumber: '1368'
                      neighborhood: Pinheiros
                      city: Sao Paulo
                      state: SP
                      country: BR
                      complement: Sala roxa
                    legalRepresentative:
                      registerName: Peter Benjamin Parker
                      socialName: Peter Parker
                      phone:
                        countryCode: '55'
                        number: '11987654321'
                      address:
                        zipCode: '05402100'
                        addressLine: Av. Rebouças
                        buildingNumber: '1368'
                        neighborhood: Pinheiros
                        city: Sao Paulo
                        state: SP
                        country: BR
                        complement: Sala roxa
                      birthDate: '1990-10-14'
                      motherName: Mary Parker
                      email: peter.parker@avengers.com
                    status: APPROVED
                    createdAt: '2021-08-31T21:20:58.754Z'
                    updatedAt: '2021-08-31T21:21:58.754Z'
                  summary: Approved Business
                BusinessRepproved:
                  value:
                    businessName: Peter Benjamin Parker
                    tradingName: Spider Man
                    businessEmail: spiderman@avengers.com
                    businessType: MEI
                    businessSize: MEI
                    businessAddress:
                      zipCode: '05402100'
                      addressLine: Av. Rebouças
                      buildingNumber: '1368'
                      neighborhood: Pinheiros
                      city: Sao Paulo
                      state: SP
                      country: BR
                      complement: Sala roxa
                    legalRepresentative:
                      registerName: Peter Benjamin Parker
                      socialName: Peter Parker
                      phone:
                        countryCode: '55'
                        number: '11987654321'
                      address:
                        zipCode: '05402100'
                        addressLine: Av. Rebouças
                        buildingNumber: '1368'
                        neighborhood: Pinheiros
                        city: Sao Paulo
                        state: SP
                        country: BR
                        complement: Sala roxa
                      birthDate: '1990-10-14'
                      motherName: Mary Parker
                      email: peter.parker@avengers.com
                    status: REPROVED
                    reasons:
                      - SELFIE_RECUSED
                      - STATUS_RECUSED
                    createdAt: '2021-08-31T21:20:58.754Z'
                    updatedAt: '2021-08-31T21:21:58.754Z'
                  summary: Reproved Business    
        '400':
          $ref: '#/components/responses/400'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'
    put:
      tags:
        - Pessoa jurídica
      summary: Registre ou atualize dos dados de um cliente pessoa física.
      description: |
        <div class="bkly-ref-description">
          <p>O pedido de registro será analisado e resultado você pode obter consultando o registro da empresa. Caso o cliente não exista ele será criado, caso contrario seus dados serão sobrepostos.</p> 
          <span class="bkly-ref-small-stable-tag">stable</span> <span class="bkly-ref-scope-tag">scope: business.write</span>
        </div>        
        [block:callout]
        {
          "type": "warning",
          "title": "Importante",
          "body": "Os possíveis status da empresa após essa análise são: APPROVED, REPROVED, REVOKED ou BLOCKED."
        }
        [/block]
      operationId: PutBusinessRegistration
      parameters:
        - $ref: '#/components/parameters/BusinessDocument'
        - $ref: '#/components/parameters/ApiVersion'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterBusinessRequest'
      responses:
        '202':
          $ref: '#/components/responses/202'
        '400':
          $ref: '#/components/responses/400'
        '409':
          $ref: '#/components/responses/409'
        '422':
          $ref: '#/components/responses/422'
        '500':
          $ref: '#/components/responses/500'
security:
  - Bearer: []
components:
  
  parameters:
    ApiVersion:
      name: api-version
      in: header
      description: Versão da API. Atualmente estamos na 1.0.
      required: true
      style: simple
      explode: false
      schema:
        type: string
        default: 1
    CustomerDocument:
      name: documentNumber
      in: path
      description: Número do documento CPF do cliente. Informe somente os números.
      required: true
      style: simple
      explode: false
      schema:
        $ref: '#/components/schemas/CustomerDocument'
    BusinessDocument:
      name: documentNumber
      in: path
      description: Número do documento CNPJ da empresa. Informe somente os números.
      required: true
      style: simple
      explode: false
      schema:
        $ref: '#/components/schemas/BusinessDocument'
    ResultLevel:
      name: resultLevel
      in: query
      description: Tipo de retorno da API. BASIC ou DETAILED
      required: false
      style: form
      explode: true
      schema:
        $ref: '#/components/schemas/ResultLevel'
  schemas:
    Error:
      type: object
      properties:
        code:
          type: string
          nullable: true
        propertyName:
          type: string
          nullable: true
        messages:
          type: array
          nullable: true
          items:
            type: string
      additionalProperties: false
    ErrorResponse:
      type: object
      properties:
        errors:
          type: array
          nullable: true
          items:
            $ref: '#/components/schemas/Error'
        reference:
          type: integer
          format: int32
      additionalProperties: false
    CustomerDocument:
      type: string
      maxLength: 11
      minLength: 11
    BusinessDocument:
      type: string
      maxLength: 14
      minLength: 14
    BusinessType:
      type: string
      description: Tipo da empresa (MEI, EI ou EIRELLI).
      enum:
        - MEI
        - EI
        - EIRELI
    BusinessSize:
      type: string
      description: Porte da empresa (MEI, ME ou EPP).
      enum:
        - MEI
        - ME
        - EPP
    Address:
      required:
        - zipCode
        - addressLine
        - buildingNumber
        - neighborhood
        - city
        - state
        - country
      type: object
      properties:
        zipCode:
          minLength: 9
          maxLength: 9
          type: string
          description: O CEP correspondente ao endereço. Informe somente os números.
        addressLine:
          maxLength: 256
          minLength: 1
          type: string
          description: |
            Logradouro (Nome da rua, avenida, etc). Caso não exista, preencha
            S/N.
        buildingNumber:
          maxLength: 10
          minLength: 1
          type: string
          description: Número da residência.
        complement:
          maxLength: 256
          type: string
          description: 'Complemento do endereço. Exemplo: Apto 123, Casa B, etc.'
          nullable: true
        neighborhood:
          maxLength: 256
          minLength: 1
          type: string
          description: Nome do bairro ou distrito.
        city:
          maxLength: 256
          minLength: 1
          type: string
          description: Nome da cidade.
        state:
          maxLength: 2
          minLength: 2
          type: string
          description: 'Sigla do estado brasileiro conforme a ISO 3166-2:BR.'
        country:
          maxLength: 2
          minLength: 2
          type: string
          description: 'Sigla do país (Brasil) conforme a ISO 3166-2. Exemplo: BR.'
      additionalProperties: false
    Phone:
      required:
        - countryCode
        - number
      type: object
      properties:
        countryCode:
          maxLength: 3
          minLength: 2
          type: string
          description: |
            Código DDI do país. Por enquanto é permitido apenas 55 ou +55
            (Brasil).
        number:
          minLength: 11
          maxLength: 11
          type: string
          description: Número de telefone incluindo DDD.
      additionalProperties: false
    LegalRepresentative:
      required:
        - documentNumber
        - registerName
        - birthDate
        - phone
        - address
        - email
        - motherName
      type: object
      properties:
        registerName:
          maxLength: 256
          minLength: 1
          type: string
          description: |
            Nome conforme consta no documento de identificação (RG ou CNH) do
            cliente.
        socialName:
          type: string
          description: >
            Nome pelo qual a pessoa gostaria de ser chamada. [Saiba

            mais](https://www.mds.gov.br/webarquivos/publicacao/assistencia_social/Folders/cartilha_nome_social.pdf)
          nullable: true
        phone:
          description: Telefone de contato do representante legal da empresa.
          $ref: '#/components/schemas/Phone'
        address:
          description: Endereço do representante legal da empresa.
          $ref: '#/components/schemas/Address'
        birthDate:
          maxLength: 10
          minLength: 10
          type: string
          description: |
            Data de nascimento do cliente. O cliente deve possuir no mínimo 16
            anos.
          format: date-time
        motherName:
          type: string
          description: |
            Nome da mãe do cliente conforme consta no documento de
            identificação.
          nullable: true
        email:
          maxLength: 256
          minLength: 1
          type: string
          description: |
            Endereço de e-mail. Um mesmo endereço de e-mail não poderá ser usado
            por dois clientes.
          format: email
        documentNumber:
          maxLength: 11
          minLength: 11
          type: string
          description: Número do documento CPF. Informe somente os números.
          readOnly: true
      additionalProperties: false
    ResultLevel:
      type: string
      description: Tipo de retorno da API (BASIC ou DETAILED).
      default: BASIC
      enum:
        - BASIC
        - DETAILED
    Status:
      type: string
      description: Status do cliente (PF).
      enum:
        - PENDING_APPROVAL
        - APPROVED
        - REPROVED
        - REVOKED
        - CANCELED
        - BLACKLISTED
    Profile:
      type: string
      description: Perfil do cliente (PF).
      enum:
        - COMPLETE
        - SIMPLE
    RegisterCustomerRequest:
      required:
        - registerName
        - birthDate
        - phone
        - address
        - email
        - motherName
      type: object
      properties:
        registerName:
          maxLength: 256
          minLength: 1
          type: string
          description: |
            Nome conforme consta no documento de identificação (RG ou CNH) do
            cliente.
        socialName:
          type: string
          description: >
            Nome pelo qual a pessoa gostaria de ser chamada. [Saiba
            mais](https://www.mds.gov.br/webarquivos/publicacao/assistencia_social/Folders/cartilha_nome_social.pdf)
          nullable: true
        phone:
          description: Telefone de contato do cliente.
          $ref: '#/components/schemas/Phone'
        address:
          description: Endereço do cliente.
          $ref: '#/components/schemas/Address'
        birthDate:
          maxLength: 10
          minLength: 10
          type: string
          description: |
            Data de nascimento do cliente. O cliente deve possuir no mínimo 16
            anos.
          format: date-time
        motherName:
          type: string
          description: |
            Nome da mãe do cliente conforme consta no documento de
            identificação.
          nullable: true
        email:
          maxLength: 256
          minLength: 1
          type: string
          description: |
            Endereço de e-mail. Um mesmo endereço de e-mail não poderá ser usado
            por dois clientes.
          format: email
      additionalProperties: false
    RegisterBusinessRequest:
      required:
        - businessName
        - tradingName
        - businessAddress
        - businessEmail
        - businessSize
        - businessType
        - legalRepresentative
      type: object
      properties:
        businessName:
          maxLength: 256
          minLength: 1
          type: string
          description: Razão social da empresa.
        tradingName:
          type: string
          description: Nome fantasia da empresa.
          nullable: true
        businessEmail:
          type: string
          description: E-mail comercial da empresa.
          format: email
          nullable: false
        businessType:
          $ref: '#/components/schemas/BusinessType'
        businessSize:
          $ref: '#/components/schemas/BusinessSize'
        businessAddress:
          description: Endereço da empresa registrado no cartão CNPJ.
          $ref: '#/components/schemas/Address'
        legalRepresentative:
          description: Representante legal da empresa.
          $ref: '#/components/schemas/LegalRepresentative'
      additionalProperties: false
    CustomerResponse:
      type: object
      properties:
        documentNumber:
          type: string
          nullable: true
        registerName:
          type: string
          nullable: true
        socialName:
          type: string
          nullable: true
        phone:
          $ref: '#/components/schemas/Phone'
        address:
          $ref: '#/components/schemas/Address'
        birthDate:
          type: string
          format: date-time
        email:
          type: string
          nullable: true
        motherName:
          type: string
          nullable: true
        isPoliticallyExposedPerson:
          type: boolean
        status:
          $ref: '#/components/schemas/Status'
        profile:
          $ref: '#/components/schemas/Profile'
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
        reasons:
          type: array
          nullable: true
          items:
            type: string
      additionalProperties: false
    BusinessResponse:
      type: object
      properties:
        documentNumber:
          type: string
          nullable: false
        businessName:
          type: string
          nullable: false
        tradingName:
          type: string
          nullable: true
        email:
          type: string
          nullable: true
        businessAddress:
          $ref: '#/components/schemas/Address'
        status:
          type: string
          nullable: false
        businessType:
          type: string
          nullable: false
        businessSize:
          type: string
          nullable: false
        owners:
          type: array
          nullable: true
          items:
            $ref: '#/components/schemas/LegalRepresentative'
        legalRepresentatives:
          type: array
          nullable: true
          items:
            $ref: '#/components/schemas/LegalRepresentative'
        createdAt:
          type: string
          format: date-time
          nullable: false
        updatedAt:
          type: string
          format: date-time
          nullable: true
        reasons:
          type: array
          nullable: true
          items:
            type: string
      additionalProperties: false
  headers:
    CorrelationId:
      description: Id correlação da operação requisitada.
      style: simple
      explode: false
      schema:
        type: string
    Location:
      description: Localização do recurso recém-criado ou em análise.
      style: simple
      explode: false
      schema:
        type: string
  responses:
    '202':
      description: Requisição foi aceita e está sendo processada.
      headers:
        x-bkly-correlation-id:
          $ref: '#/components/headers/CorrelationId'
        Location:
          $ref: '#/components/headers/Location'
    '400':
      description: Há algum problema com a sua requisição.
      headers:
        x-bkly-correlation-id:
          $ref: '#/components/headers/CorrelationId'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          examples:
            accountDetailedExample:
              $ref: '#/components/examples/invalidParameterErrorResponse'
    '404':
      description: |
        Recurso não encontrado.
      headers:
        x-bkly-correlation-id:
          $ref: '#/components/headers/CorrelationId'
    '409':
      description: |
        A solicitação conflitou com o estado atual do recurso existente no
        servidor.
      headers:
        x-bkly-correlation-id:
          $ref: '#/components/headers/CorrelationId'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          examples:
            accountDetailedExample:
              $ref: '#/components/examples/errorResponse'
    '422':
      description: |
        A sintaxe da requisição esta correta, mas não foi possível processar
        devido uma regra de negócio.
      headers:
        x-bkly-correlation-id:
          $ref: '#/components/headers/CorrelationId'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          examples:
            accountDetailedExample:
              $ref: '#/components/examples/errorResponse'
    '500':
      description: |
        Ocorreu algum erro inexperado no nosso servidor.
      headers:
        x-bkly-correlation-id:
          $ref: '#/components/headers/CorrelationId'
  securitySchemes:
    Bearer:
      type: http
      description: Inclua o token de autorização do tipo Bearer
      scheme: bearer
      bearerFormat: JWT
  examples:
    invalidParameterErrorResponse:
      value:
        errors:
          - code: INVALID_PARAMETER
            propertyName: '{{propertyName}}'
            messages:
              - '{{"propertyName" error message}}'
      summary: Invalid parameter error
    errorResponse:
      value:
        errors:
          - code: SOME_ERROR_CODE
            messages:
              - '{{Some error message}}'
      summary: Business error
x-readme:
  explorer-enabled: true
  proxy-enabled: true
  samples-enabled: true
  samples-languages:
    - curl
